name: ❓ Question
description: Ask a question about using AiFinPay × Casper
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve? What have you tried?
